//=============================================================================
// DO NOT EDIT THIS FILE!!!!!
//=============================================================================

#include <stdio.h>
#include <stdlib.h>
#include <error.h>
#include  <inttypes.h>

extern unsigned int quidFP2float(unsigned int);

union uf {
  unsigned int i;
  float f;
};
typedef union uf uf_t;


int main(int argc, char *argv[]){

  uf_t cvt;
  FILE *fp;
  if ((fp = fopen(argv[1], "r")) == NULL){
    fclose(fp);

  }

  uint8_t quidditchfp;
  while(fread(&endorFP, 1, 1, fp)){
    cvt.i = quidFP2float((uint32_t)quidditchfp);
    printf("%02x\t", quidditchfp);
    printf("%08x\t", cvt.i);
    printf("%12.7f\n", cvt.f);
  }

  fclose(fp);
}
